
version: '3'

services:
  bdreader:
    build: .
    container_name: bdreader
    restart: unless-stopped
    volumes:
      - /home/pi/Library:/root/Library
      - bd-data:/root/data
    ports:
      - "8080:80"
    labels:
      - autoheal=true
      
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  bd-data:
    external: true